# Generated by Django 5.0.4 on 2024-04-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userpropertyimage_delete_overview_property_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpropertyimage',
            name='user_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='app.user_property'),
        ),
    ]
