# Generated by Django 5.0.4 on 2024-04-20 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_userpropertyimage_user_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpropertyimage',
            name='user_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.user_property'),
        ),
    ]
