# Generated by Django 5.0.4 on 2024-04-20 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_userpropertyimage_user_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_property',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, null=True, size=None),
        ),
        migrations.DeleteModel(
            name='UserPropertyImage',
        ),
    ]
