# Generated by Django 5.0.4 on 2024-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_property_images_delete_userpropertyimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_property',
            old_name='paid',
            new_name='paid_amount',
        ),
        migrations.AddField(
            model_name='user_property',
            name='property_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
