# Generated by Django 5.0.4 on 2024-04-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_paid_user_property_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_property',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
